// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto_Final.Data.Contexto;

#nullable disable

namespace Proyecto_Final.Data.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20241125154621_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proyecto_Final.Data.Models.Clientes", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Provicia")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Proyecto_Final.Data.Models.Imagen", b =>
                {
                    b.Property<int>("ImagenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImagenId"));

                    b.Property<string>("Alt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ViajeId")
                        .HasColumnType("int");

                    b.HasKey("ImagenId");

                    b.HasIndex("ViajeId");

                    b.ToTable("Imagenes");

                    b.HasData(
                        new
                        {
                            ImagenId = 1,
                            Alt = "Imagen 1",
                            ImagenUrl = "Images/Bahia-Aguilas.jpg",
                            Titulo = "Bahia de las aguilas",
                            ViajeId = 1
                        },
                        new
                        {
                            ImagenId = 2,
                            Alt = "Imagen 2",
                            ImagenUrl = "Images/camino-rocoso.jpg",
                            Titulo = "Camino roscoso",
                            ViajeId = 1
                        },
                        new
                        {
                            ImagenId = 3,
                            Alt = "Imagen 3",
                            ImagenUrl = "Images/Punta-Cana.jpg",
                            Titulo = "Punta cana",
                            ViajeId = 2
                        });
                });

            modelBuilder.Entity("Proyecto_Final.Data.Models.Taxistas", b =>
                {
                    b.Property<int>("TaxistaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaxistaId"));

                    b.Property<int?>("ClientesClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ExisteLicencia")
                        .HasColumnType("bit");

                    b.Property<bool>("ExisteVehiculo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Provicia")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("TaxistaId");

                    b.HasIndex("ClientesClienteId");

                    b.ToTable("Taxistas");

                    b.HasData(
                        new
                        {
                            TaxistaId = 1,
                            Correo = "federicoLiranzo01@gmail.com",
                            ExisteLicencia = true,
                            ExisteVehiculo = true,
                            FechaNacimiento = new DateTime(1985, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NickName = "Federico Liranzo",
                            Password = "elcompa1985",
                            Role = 1,
                            Status = 1
                        },
                        new
                        {
                            TaxistaId = 2,
                            Correo = "cesarpolanco1@gmail.com",
                            ExisteLicencia = true,
                            ExisteVehiculo = true,
                            FechaNacimiento = new DateTime(1995, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NickName = "Cesar Polanco",
                            Password = "sorollo1995",
                            Role = 1,
                            Status = 1
                        },
                        new
                        {
                            TaxistaId = 3,
                            Correo = "martinperez90@gmail.com",
                            ExisteLicencia = true,
                            ExisteVehiculo = false,
                            FechaNacimiento = new DateTime(1990, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NickName = "Martin Perez",
                            Password = "eltino1990",
                            Role = 1,
                            Status = 1
                        },
                        new
                        {
                            TaxistaId = 4,
                            Correo = "juanrodriguez87@gmail.com",
                            ExisteLicencia = false,
                            ExisteVehiculo = true,
                            FechaNacimiento = new DateTime(1987, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NickName = "Juan Rodríguez",
                            Password = "rapido1987",
                            Role = 1,
                            Status = 1
                        },
                        new
                        {
                            TaxistaId = 5,
                            Correo = "carlosherrera92@gmail.com",
                            ExisteLicencia = true,
                            ExisteVehiculo = true,
                            FechaNacimiento = new DateTime(1992, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NickName = "Carlos Herrera",
                            Password = "chico1992",
                            Role = 1,
                            Status = 1
                        });
                });

            modelBuilder.Entity("Proyecto_Final.Data.Models.Viajes", b =>
                {
                    b.Property<int>("ViajeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ViajeId"));

                    b.Property<int?>("ClientesClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.Property<int>("TaxistaId")
                        .HasColumnType("int");

                    b.Property<int>("personas")
                        .HasColumnType("int");

                    b.HasKey("ViajeId");

                    b.HasIndex("ClientesClienteId");

                    b.HasIndex("TaxistaId");

                    b.ToTable("Viajes");

                    b.HasData(
                        new
                        {
                            ViajeId = 1,
                            Destino = " Bania de las aguilas",
                            Estado = 2,
                            Fecha = new DateTime(2024, 11, 25, 11, 46, 21, 250, DateTimeKind.Local).AddTicks(9638),
                            Precio = 2500.0,
                            TaxistaId = 1,
                            personas = 5
                        },
                        new
                        {
                            ViajeId = 2,
                            Destino = "Punta Cana",
                            Estado = 2,
                            Fecha = new DateTime(2024, 11, 25, 11, 46, 21, 250, DateTimeKind.Local).AddTicks(9659),
                            Precio = 3500.0,
                            TaxistaId = 3,
                            personas = 5
                        });
                });

            modelBuilder.Entity("Proyecto_Final.Data.Models.Imagen", b =>
                {
                    b.HasOne("Proyecto_Final.Data.Models.Viajes", "Viaje")
                        .WithMany("Imagenes")
                        .HasForeignKey("ViajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Viaje");
                });

            modelBuilder.Entity("Proyecto_Final.Data.Models.Taxistas", b =>
                {
                    b.HasOne("Proyecto_Final.Data.Models.Clientes", null)
                        .WithMany("Favoritos")
                        .HasForeignKey("ClientesClienteId");
                });

            modelBuilder.Entity("Proyecto_Final.Data.Models.Viajes", b =>
                {
                    b.HasOne("Proyecto_Final.Data.Models.Clientes", null)
                        .WithMany("Viajes")
                        .HasForeignKey("ClientesClienteId");

                    b.HasOne("Proyecto_Final.Data.Models.Taxistas", "Taxista")
                        .WithMany()
                        .HasForeignKey("TaxistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Taxista");
                });

            modelBuilder.Entity("Proyecto_Final.Data.Models.Clientes", b =>
                {
                    b.Navigation("Favoritos");

                    b.Navigation("Viajes");
                });

            modelBuilder.Entity("Proyecto_Final.Data.Models.Viajes", b =>
                {
                    b.Navigation("Imagenes");
                });
#pragma warning restore 612, 618
        }
    }
}
